name: Unity CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  editmode-tests:
    name: EditMode Tests
    runs-on: ubuntu-latest
    if: ${{ secrets.UNITY_LICENSE != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-
      - name: Run EditMode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 6000.2.1f1
          testMode: EditMode
          projectPath: .

  addressables-build-dev:
    name: Addressables Dev Build
    runs-on: ubuntu-latest
    needs: editmode-tests
    if: ${{ always() && secrets.UNITY_LICENSE != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-
      - name: Addressables Build (Dev)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 6000.2.1f1
          projectPath: .
          buildName: AddressablesDev
          targetPlatform: StandaloneOSX
          customParameters: -quit -batchmode -nographics -executeMethod WWIII.SideScroller.Editor.Addressables.AddressablesBuildMenu.BuildPlayerContentCI

